### ISSUE TITLE
@conda-forge-admin, please add user @mfisher87

### ISSUE THREAD

**Issue by mfisher87** [conda-forge/pangeo-forge-runner-feedstock#19]

**Comment by weiji14** [comment]
Thanks @mfisher87 for volunteering to help with maintenance here. For the two other users at #21 and #23, could you get them to confirm in writing that they're actually willing to be added as recipe maintainers?

**Comment by mfisher87** [comment]
Absolutely :) For context, we are the dev team for the "QGreenland-Net" project and we're just getting kicked off and considering how we can collaborate with Pangeo Forge. We'll probably be pestering you with more questions in Slack :)

**Comment by weiji14** [comment]
Nice, always glad to see some exciting work on open science! I'm actually not a pangeo-forge developer to be honest, only here because I was helping a colleague who wanted a newer v0.9.0 version (https://github.com/conda-forge/pangeo-forge-runner-feedstock/pull/4#pullrequestreview-1698523446), so best to direct pangeo-forge specific questions to https://github.com/pangeo-forge/pangeo-forge-recipes :slightly_smiling_face:
